# Generated by Django 5.0.6 on 2024-07-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="descricao",
        ),
        migrations.AddField(
            model_name="produto",
            name="preco",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
