# Generated by Django 5.0.6 on 2024-07-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_remove_produto_created_date_remove_produto_descricao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("endereco", models.CharField(max_length=500)),
                ("idade", models.DateField()),
            ],
        ),
    ]
