# Generated by Django 5.0.6 on 2024-07-11 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0004_rename_fornecedor_fornecedores"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Fornecedores",
            new_name="Fornecedor",
        ),
    ]
