# Generated by Django 5.0.6 on 2024-08-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0006_produto_quantidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="produto",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="loja.produto",
            ),
        ),
    ]
