# Generated by Django 5.0.6 on 2024-08-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0007_fornecedor_produto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedor",
            name="produto",
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="produto",
            field=models.ManyToManyField(default=1, to="loja.produto"),
        ),
    ]
